### Importing Libraries

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing Dataset

In [2]:
dataset = pd.read_csv('ToyotaCorolla.csv')

In [6]:
dataset.columns

Index(['Id', 'Model', 'Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM',
       'Fuel_Type', 'HP', 'Met_Color', 'Color', 'Automatic', 'cc', 'Doors',
       'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee',
       'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2',
       'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player',
       'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio',
       'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Tow_Bar'],
      dtype='object')

### Concatenate different columns (Data Preprocessing)

In [11]:
df=pd.concat([dataset.iloc[:,2:4],dataset.iloc[:,6:7],dataset.iloc[:,8:9],dataset.iloc[:,12:14],dataset.iloc[:,15:18]],axis=1)

In [12]:
df.head()

   Price  Age_08_04     KM  HP    cc  Doors  Gears  Quarterly_Tax  Weight
0  13500         23  46986  90  2000      3      5            210    1165
1  13750         23  72937  90  2000      3      5            210    1165
2  13950         24  41711  90  2000      3      5            210    1165
3  14950         26  48000  90  2000      3      5            210    1165
4  13750         30  38500  90  2000      3      5            210    1170

In [37]:
df.rename(columns={'Age_08_04':'Age','Quarterly_Tax':'QTAX'},inplace=True)

In [38]:
df.head()

   Price  Age     KM  HP    cc  Doors  Gears  QTAX  Weight
0  13500   23  46986  90  2000      3      5   210    1165
1  13750   23  72937  90  2000      3      5   210    1165
2  13950   24  41711  90  2000      3      5   210    1165
3  14950   26  48000  90  2000      3      5   210    1165
4  13750   30  38500  90  2000      3      5   210    1170

### Selecting X and Y variables

In [44]:
x=df.iloc[:,1:9].values
y=df.iloc[:,:1].values

In [45]:
print(x)

[[   23 46986    90 ...     5   210  1165]
 [   23 72937    90 ...     5   210  1165]
 [   24 41711    90 ...     5   210  1165]
 ...
 [   71 17016    86 ...     5    69  1015]
 [   70 16916    86 ...     5    69  1015]
 [   76     1   110 ...     5    19  1114]]

In [46]:
print(y)

[[13500]
 [13750]
 [13950]
 ...
 [ 8500]
 [ 7250]
 [ 6950]]

### Splitting Data in train and test set

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [48]:
print(y_test)

[[ 7950]
 [10950]
 [14950]
 [ 7500]
 [ 9900]
 [ 8900]
 [ 6950]
 [15750]
 [11950]
 [ 9930]
 [ 8500]
 [10450]
 [11895]
 [ 9950]
 [ 6450]
 [15500]
 [11950]
 [ 6900]
 [10950]
 [ 9750]
 [ 7350]
 [ 8950]
 [13750]
 [14950]
 [19950]
 [ 9450]
 [11500]
 [ 8500]
 [ 9450]
 [ 8800]
 [11450]
 [10500]
 [13750]
 [ 8250]
 [10950]
 [11950]
 [ 8950]
 [12900]
 [ 9500]
 [ 9950]
 [ 8950]
 [ 9500]
 [ 9950]
 [15500]
 [10950]
 [ 7500]
 [ 9450]
 [ 9500]
 [10845]
 [ 8500]
 [19750]
 [ 8950]
 [ 7250]
 [ 6750]
 [10950]
 [19950]
 [11000]
 [ 8950]
 [17795]
 [10500]
 [ 5740]
 [ 7750]
 [10950]
 [10500]
 [12500]
 [12900]
 [ 8450]
 [ 7950]
 [19450]
 [11450]
 [ 9500]
 [ 4450]
 [11690]
 [ 7900]
 [14750]
 [14990]
 [ 9950]
 [ 7450]
 [ 6950]
 [ 8250]
 [ 6750]
 [ 6900]
 [ 5950]
 [12750]
 [11950]
 [10750]
 [ 8950]
 [11950]
 [ 8250]
 [ 7450]
 [ 6950]
 [10750]
 [17450]
 [ 9940]
 [ 7950]
 [12250]
 [12950]
 [10950]
 [12450]
 [ 6900]
 [ 8500]
 [10750]
 [ 9700]
 [ 9250]
 [ 7900]
 [19000]
 [18450]
 [ 8500]
 [13250]
 [10400]
 [12500]
 [ 9200]
 [ 8500]
 [ 8250]
 [13750]
 [ 8950]
 [ 7950]
 [10950]
 [ 9900]
 [ 7750]
 [20500]
 [ 9950]
 [13995]
 [10250]
 [ 7950]
 [23950]
 [ 7950]
 [11500]
 [ 9250]
 [ 9950]
 [17950]
 [ 8950]
 [ 9980]
 [10500]
 [21125]
 [11950]
 [11950]
 [12450]
 [ 7995]
 [13500]
 [15750]
 [ 8850]
 [ 8750]
 [ 7750]
 [ 9895]
 [20750]
 [11950]
 [13950]
 [10950]
 [11950]
 [ 7950]
 [12950]
 [ 9950]
 [ 8950]
 [11450]
 [16950]
 [ 9900]
 [ 8950]
 [ 8450]
 [ 8750]
 [ 7400]
 [ 8500]
 [ 7800]
 [16750]
 [ 9950]
 [ 6450]
 [21950]
 [ 8750]
 [ 8200]
 [15800]
 [10450]
 [10900]
 [ 9950]
 [ 7500]
 [ 8250]
 [ 9950]
 [ 8250]
 [11900]
 [16450]
 [ 9995]
 [10950]
 [ 8950]
 [ 9250]
 [14750]
 [11450]
 [ 8750]
 [ 8950]
 [13950]
 [13750]
 [ 5950]
 [ 9950]
 [ 8500]
 [ 4750]
 [10950]
 [10950]
 [ 8950]
 [18950]
 [ 8950]
 [ 7950]
 [ 6500]
 [ 9900]
 [10750]
 [13950]
 [15250]
 [11500]
 [ 8750]
 [10450]
 [11950]
 [ 8950]
 [ 6950]
 [10950]
 [ 6950]
 [ 9250]
 [ 7950]
 [ 7250]
 [17950]
 [22500]
 [10500]
 [ 7600]
 [10950]
 [ 6900]
 [ 6500]
 [ 9950]
 [ 9800]
 [12950]
 [ 9950]
 [ 9450]
 [16950]
 [ 9950]
 [10950]
 [ 7750]
 [10950]
 [ 8750]
 [12950]
 [ 8050]
 [ 8950]
 [ 7450]
 [ 7950]
 [ 8250]
 [14950]
 [ 8695]
 [ 9950]
 [ 5950]
 [ 7950]
 [18950]
 [ 7200]
 [12950]
 [ 6950]
 [11950]
 [ 8950]
 [ 8750]
 [ 7750]
 [12950]
 [ 9450]
 [ 7500]
 [10000]
 [ 9900]
 [16500]
 [ 8950]
 [10750]
 [19950]
 [ 9950]
 [14750]
 [ 6900]
 [13950]
 [ 8950]
 [16950]
 [ 9800]
 [ 7950]
 [ 9450]
 [12900]
 [ 8950]
 [10750]
 [13950]
 [ 6950]
 [19500]
 [21500]
 [ 7450]
 [ 9950]
 [11500]
 [ 6900]
 [ 8450]
 [ 5250]
 [10450]
 [ 9400]
 [ 9950]
 [11750]
 [ 7950]]

### Model Creation and testing on train and test models

In [49]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

### R-Squared

In [50]:
regressor.score(x,y)

0.821734577742414

### Predicting Test Score(Comparing predicted value of y and actual test value of y)

In [51]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[  8289.01   7950.  ]
 [ 10517.    10950.  ]
 [ 13010.62  14950.  ]
 [  7666.6    7500.  ]
 [ 10486.85   9900.  ]
 [  9543.84   8900.  ]
 [  6140.54   6950.  ]
 [ 16218.43  15750.  ]
 [ 11289.5   11950.  ]
 [ 10499.56   9930.  ]
 [  6892.08   8500.  ]
 [ 11225.26  10450.  ]
 [ 11819.05  11895.  ]
 [  9744.71   9950.  ]
 [  7432.58   6450.  ]
 [ 16111.69  15500.  ]
 [ 11172.06  11950.  ]
 [  7751.06   6900.  ]
 [ 12849.54  10950.  ]
 [  8517.49   9750.  ]
 [  6731.21   7350.  ]
 [  6053.79   8950.  ]
 [ 11666.32  13750.  ]
 [ 13024.83  14950.  ]
 [ 18991.79  19950.  ]
 [  7748.68   9450.  ]
 [ 14050.56  11500.  ]
 [  5742.64   8500.  ]
 [  9247.59   9450.  ]
 [  7885.92   8800.  ]
 [ 10609.46  11450.  ]
 [  7647.1   10500.  ]
 [ 16093.34  13750.  ]
 [  7226.74   8250.  ]
 [ 11013.83  10950.  ]
 [ 12532.57  11950.  ]
 [  9733.86   8950.  ]
 [ 12230.39  12900.  ]
 [  9782.11   9500.  ]
 [  9006.26   9950.  ]
 [  8847.43   8950.  ]
 [ 10623.31   9500.  ]
 [  9952.96   9950.  ]
 [ 17009.32  15500.  ]
 [ 10970.31  10950.  ]
 [  7067.04   7500.  ]
 [  9631.08   9450.  ]
 [  7338.86   9500.  ]
 [  8442.51  10845.  ]
 [  8772.6    8500.  ]
 [ 19094.18  19750.  ]
 [  8457.36   8950.  ]
 [  7194.09   7250.  ]
 [  6534.06   6750.  ]
 [ 11461.18  10950.  ]
 [ 18149.57  19950.  ]
 [ 13550.95  11000.  ]
 [ 10115.11   8950.  ]
 [ 18934.58  17795.  ]
 [ 11003.2   10500.  ]
 [  6518.58   5740.  ]
 [  7846.06   7750.  ]
 [ 11078.83  10950.  ]
 [ 12211.31  10500.  ]
 [ 10417.14  12500.  ]
 [ 13971.77  12900.  ]
 [  8313.7    8450.  ]
 [  6862.94   7950.  ]
 [ 17479.78  19450.  ]
 [ 10703.29  11450.  ]
 [  9832.46   9500.  ]
 [  8634.14   4450.  ]
 [ 13337.01  11690.  ]
 [  6214.84   7900.  ]
 [ 14768.67  14750.  ]
 [ 13188.12  14990.  ]
 [ 10774.7    9950.  ]
 [  6847.37   7450.  ]
 [  8153.15   6950.  ]
 [  8132.81   8250.  ]
 [  6816.54   6750.  ]
 [  8692.14   6900.  ]
 [  6076.71   5950.  ]
 [ 11762.21  12750.  ]
 [ 11964.89  11950.  ]
 [ 10576.05  10750.  ]
 [ 11467.74   8950.  ]
 [ 12404.43  11950.  ]
 [  7956.82   8250.  ]
 [  9531.58   7450.  ]
 [  6405.57   6950.  ]
 [ 10333.84  10750.  ]
 [ 16569.7   17450.  ]
 [ 12803.8    9940.  ]
 [  8115.94   7950.  ]
 [ 12175.85  12250.  ]
 [ 15437.04  12950.  ]
 [ 10013.11  10950.  ]
 [ 13445.78  12450.  ]
 [  7564.71   6900.  ]
 [  8346.47   8500.  ]
 [ 11804.03  10750.  ]
 [ 11859.07   9700.  ]
 [  8289.79   9250.  ]
 [  8319.42   7900.  ]
 [ 18264.01  19000.  ]
 [ 18214.6   18450.  ]
 [  8233.36   8500.  ]
 [ 14277.96  13250.  ]
 [  8660.26  10400.  ]
 [ 13576.45  12500.  ]
 [  9201.93   9200.  ]
 [ 10430.91   8500.  ]
 [  9488.9    8250.  ]
 [ 13183.4   13750.  ]
 [  9175.31   8950.  ]
 [  9284.33   7950.  ]
 [ 12593.5   10950.  ]
 [  9378.29   9900.  ]
 [  8179.58   7750.  ]
 [ 17068.62  20500.  ]
 [  7418.41   9950.  ]
 [ 14001.49  13995.  ]
 [ 10127.28  10250.  ]
 [  8014.42   7950.  ]
 [ 20384.68  23950.  ]
 [  7049.82   7950.  ]
 [ 10145.55  11500.  ]
 [  9309.28   9250.  ]
 [ 10385.09   9950.  ]
 [ 17109.64  17950.  ]
 [  9033.99   8950.  ]
 [ 11305.69   9980.  ]
 [  9915.16  10500.  ]
 [ 19432.53  21125.  ]
 [ 11110.23  11950.  ]
 [ 12475.18  11950.  ]
 [ 12966.64  12450.  ]
 [ 10292.86   7995.  ]
 [ 13531.46  13500.  ]
 [ 15695.81  15750.  ]
 [ 10293.73   8850.  ]
 [  8752.27   8750.  ]
 [  7823.91   7750.  ]
 [  9178.61   9895.  ]
 [ 17368.9   20750.  ]
 [ 10468.4   11950.  ]
 [ 12705.29  13950.  ]
 [ 11079.18  10950.  ]
 [ 12364.96  11950.  ]
 [  7831.81   7950.  ]
 [ 13376.87  12950.  ]
 [ 10097.53   9950.  ]
 [  6860.03   8950.  ]
 [ 11133.82  11450.  ]
 [ 14846.23  16950.  ]
 [ 10171.25   9900.  ]
 [  9743.4    8950.  ]
 [  7650.2    8450.  ]
 [  8546.08   8750.  ]
 [  7989.08   7400.  ]
 [  9160.86   8500.  ]
 [  8425.63   7800.  ]
 [ 14989.83  16750.  ]
 [ 11163.96   9950.  ]
 [  8819.65   6450.  ]
 [ 19690.82  21950.  ]
 [  9174.25   8750.  ]
 [  9061.07   8200.  ]
 [ 15632.94  15800.  ]
 [  9944.05  10450.  ]
 [ 10661.17  10900.  ]
 [  9861.13   9950.  ]
 [  8207.52   7500.  ]
 [  8130.45   8250.  ]
 [ 10723.76   9950.  ]
 [  8743.18   8250.  ]
 [ 12917.87  11900.  ]
 [ 16840.54  16450.  ]
 [ 10708.39   9995.  ]
 [ 11430.81  10950.  ]
 [  9254.79   8950.  ]
 [  7753.47   9250.  ]
 [ 15754.41  14750.  ]
 [ 12687.18  11450.  ]
 [  9200.93   8750.  ]
 [  9468.78   8950.  ]
 [ 16659.    13950.  ]
 [ 16205.55  13750.  ]
 [  6844.27   5950.  ]
 [ 10006.52   9950.  ]
 [  8260.25   8500.  ]
 [ 10048.83   4750.  ]
 [ 12448.63  10950.  ]
 [ 10353.18  10950.  ]
 [  7745.43   8950.  ]
 [ 17731.9   18950.  ]
 [  7571.51   8950.  ]
 [  7633.22   7950.  ]
 [  5252.78   6500.  ]
 [  9613.42   9900.  ]
 [ 12283.04  10750.  ]
 [ 13369.38  13950.  ]
 [ 15491.96  15250.  ]
 [ 11151.21  11500.  ]
 [  9892.27   8750.  ]
 [ 12518.91  10450.  ]
 [ 10649.25  11950.  ]
 [  8733.37   8950.  ]
 [  6411.28   6950.  ]
 [ 13575.42  10950.  ]
 [  8442.92   6950.  ]
 [  8555.06   9250.  ]
 [  7070.1    7950.  ]
 [  7068.45   7250.  ]
 [ 16132.68  17950.  ]
 [ 19836.45  22500.  ]
 [ 10842.58  10500.  ]
 [  8168.27   7600.  ]
 [ 12176.97  10950.  ]
 [  7588.32   6900.  ]
 [  7705.45   6500.  ]
 [ 10714.84   9950.  ]
 [  8417.52   9800.  ]
 [ 13541.06  12950.  ]
 [ 10585.87   9950.  ]
 [  9986.04   9450.  ]
 [ 17396.66  16950.  ]
 [ 10850.7    9950.  ]
 [ 10814.32  10950.  ]
 [  8477.72   7750.  ]
 [ 10451.46  10950.  ]
 [ 10447.7    8750.  ]
 [ 14334.16  12950.  ]
 [  6974.33   8050.  ]
 [  9409.72   8950.  ]
 [  7487.45   7450.  ]
 [  7021.49   7950.  ]
 [  8507.65   8250.  ]
 [ 13531.96  14950.  ]
 [ 11076.26   8695.  ]
 [  9266.91   9950.  ]
 [  6910.84   5950.  ]
 [  9042.84   7950.  ]
 [-10990.45  18950.  ]
 [  7720.62   7200.  ]
 [ 11759.13  12950.  ]
 [ 11231.78   6950.  ]
 [ 10387.84  11950.  ]
 [  9172.56   8950.  ]
 [  8417.21   8750.  ]
 [  8759.88   7750.  ]
 [ 12223.07  12950.  ]
 [ 10337.39   9450.  ]
 [ 15153.6    7500.  ]
 [  8893.6   10000.  ]
 [  9581.27   9900.  ]
 [ 16163.83  16500.  ]
 [  8414.9    8950.  ]
 [  9422.99  10750.  ]
 [ 19885.58  19950.  ]
 [ 10173.16   9950.  ]
 [ 15347.8   14750.  ]
 [  8981.96   6900.  ]
 [ 15963.4   13950.  ]
 [ 10066.04   8950.  ]
 [ 16511.01  16950.  ]
 [  8435.32   9800.  ]
 [  7625.81   7950.  ]
 [ 10397.93   9450.  ]
 [ 12239.83  12900.  ]
 [  9988.64   8950.  ]
 [ 11345.84  10750.  ]
 [ 11939.61  13950.  ]
 [  8851.04   6950.  ]
 [ 17459.03  19500.  ]
 [ 20098.14  21500.  ]
 [  6543.99   7450.  ]
 [  8532.76   9950.  ]
 [ 13201.81  11500.  ]
 [  7416.95   6900.  ]
 [  8960.32   8450.  ]
 [  7226.31   5250.  ]
 [ 11406.05  10450.  ]
 [ 10421.96   9400.  ]
 [ 10104.78   9950.  ]
 [ 12776.96  11750.  ]
 [  7322.2    7950.  ]]